### ISSUE TITLE
grsat-wrapper IPv6

### ISSUE THREAD

**Issue by fojtp** [kng/satnogs_gr-satellites#16]
If I have an RPi with IPv6 disabled, it will listen on IPv6 by default and crash with:
`RuntimeError: open: Address family not supported by protocol`

It would be possible to change:
`GROPT="$NORAD --samp_rate $SAMP --iq --udp --udp_port $UDP_DUMP_PORT --udp_raw --start_time $DATEF --kiss_out $KSS --ignore_unknown_args --satcfg"
`

to

`GROPT="$NORAD --samp_rate $SAMP --iq --udp --udp_ip 0.0.0.0 --udp_port $UDP_DUMP_PORT --udp_raw --start_time $DATEF --kiss_out $KSS --ignore_unknown_args --satcfg"`

or add a configurable variable for `--udp-ip`?

with the setting `--udp_ip 0.0.0.0` IPv6 can remain disabled.

The same case is of course also in docker (knegge/satnogs-client:lsf-addons)

**Comment by kng** [comment]
I first thought I should just add a `$GRSAT_EXTRA` that can pass any extra arguments to `gr_satellites`, but the fix for this particular issue is probably to use `--udp_ip` on the already set `$UDP_DUMP_HOST`

If you can test this:
`GROPT="$NORAD --samp_rate $SAMP --iq --udp --udp_ip $UDP_DUMP_HOST --udp_port $UDP_DUMP_PORT --udp_raw --start_time $DATEF --kiss_out $KSS --ignore_unknown_args --satcfg"`

I think we should add a default of `0.0.0.0` at line [45](https://github.com/kng/satnogs_gr-satellites/blob/main/grsat-wrapper.sh#L45) in that case.

**Comment by kng** [comment]
However, there's a compatibility issue here:
[maint-3.8](https://github.com/daniestevez/gr-satellites/blob/maint-3.8/apps/gr_satellites#L87-L89) has `--udp_ip` but [main](https://github.com/daniestevez/gr-satellites/blob/main/apps/gr_satellites#L94-L95) has `--udp_ipv4_only` instead, this is probably due to the changes in GNU Radio [UDP Source](https://wiki.gnuradio.org/index.php/UDP_Source).

**Comment by kng** [comment]
Implemented in [6ee834e](https://github.com/kng/satnogs_gr-satellites/commit/6ee834eb10b4701895ceed1a60758b995c46473b)
